include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    # Additional rules
    prefer_single_quotes: true
    sort_child_properties_last: true
    use_key_in_widget_constructors: true 